//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_AracKiralamaEntities : DbContext
    {
        public Db_AracKiralamaEntities()
            : base("name=Db_AracKiralamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb1_Araclar> Tb1_Araclar { get; set; }
        public virtual DbSet<Tb1_Rezervasyonlar> Tb1_Rezervasyonlar { get; set; }
        public virtual DbSet<Tb1_Musteriler> Tb1_Musteriler { get; set; }
    }
}
